-- Task 05 — Product Master permissions, granted to the bootstrap admin role.

INSERT INTO permissions (id, code, module, resource, action, description) VALUES
(26, 'product.view',       'product', 'product',       'view',       'View products'),
(27, 'product.create',     'product', 'product',       'create',     'Create products'),
(28, 'product.update',     'product', 'product',       'update',     'Update products'),
(29, 'product.deactivate', 'product', 'product',       'deactivate', 'Deactivate products'),
(30, 'unit.view',                 'product', 'unit',                 'view',       'View units'),
(31, 'unit.create',               'product', 'unit',                 'create',     'Create units'),
(32, 'unit.update',               'product', 'unit',                 'update',     'Update units'),
(33, 'unit.deactivate',           'product', 'unit',                 'deactivate', 'Deactivate units'),
(34, 'active_ingredient.view',       'product', 'active_ingredient', 'view',       'View active ingredients'),
(35, 'active_ingredient.create',     'product', 'active_ingredient', 'create',     'Create active ingredients'),
(36, 'active_ingredient.update',     'product', 'active_ingredient', 'update',     'Update active ingredients'),
(37, 'active_ingredient.deactivate', 'product', 'active_ingredient', 'deactivate', 'Deactivate active ingredients'),
(38, 'brand.view',       'product', 'brand',       'view',       'View brands'),
(39, 'brand.create',     'product', 'brand',       'create',     'Create brands'),
(40, 'brand.update',     'product', 'brand',       'update',     'Update brands'),
(41, 'brand.deactivate', 'product', 'brand',       'deactivate', 'Deactivate brands'),
(42, 'generic.view',       'product', 'generic',       'view',       'View generics'),
(43, 'generic.create',     'product', 'generic',       'create',     'Create generics'),
(44, 'generic.update',     'product', 'generic',       'update',     'Update generics'),
(45, 'generic.deactivate', 'product', 'generic',       'deactivate', 'Deactivate generics'),
(46, 'dosage_form.view',       'product', 'dosage_form',       'view',       'View dosage forms'),
(47, 'dosage_form.create',     'product', 'dosage_form',       'create',     'Create dosage forms'),
(48, 'dosage_form.update',     'product', 'dosage_form',       'update',     'Update dosage forms'),
(49, 'dosage_form.deactivate', 'product', 'dosage_form',       'deactivate', 'Deactivate dosage forms'),
(50, 'route.view',       'product', 'route',       'view',       'View routes'),
(51, 'route.create',     'product', 'route',       'create',     'Create routes'),
(52, 'route.update',     'product', 'route',       'update',     'Update routes'),
(53, 'route.deactivate', 'product', 'route',       'deactivate', 'Deactivate routes'),
(54, 'category.view',       'product', 'category',       'view',       'View categories'),
(55, 'category.create',     'product', 'category',       'create',     'Create categories'),
(56, 'category.update',     'product', 'category',       'update',     'Update categories'),
(57, 'category.deactivate', 'product', 'category',       'deactivate', 'Deactivate categories'),
(58, 'therapeutic_category.view',       'product', 'therapeutic_category',       'view',       'View therapeutic categories'),
(59, 'therapeutic_category.create',     'product', 'therapeutic_category',       'create',     'Create therapeutic categories'),
(60, 'therapeutic_category.update',     'product', 'therapeutic_category',       'update',     'Update therapeutic categories'),
(61, 'therapeutic_category.deactivate', 'product', 'therapeutic_category',       'deactivate', 'Deactivate therapeutic categories'),
(62, 'manufacturer.view',       'product', 'manufacturer',       'view',       'View manufacturers'),
(63, 'manufacturer.create',     'product', 'manufacturer',       'create',     'Create manufacturers'),
(64, 'manufacturer.update',     'product', 'manufacturer',       'update',     'Update manufacturers'),
(65, 'manufacturer.deactivate', 'product', 'manufacturer',       'deactivate', 'Deactivate manufacturers');

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT 1, id FROM permissions WHERE id >= 26;
