-- Task 11 — Patients, Prescribers, Prescriptions, Prescription Lines, Refills, Attachments.

CREATE TABLE IF NOT EXISTS patients (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id INT UNSIGNED NOT NULL,
  patient_number VARCHAR(50) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  gender ENUM('male', 'female', 'other') NOT NULL,
  date_of_birth DATE NOT NULL,
  phone VARCHAR(50) NULL,
  email VARCHAR(100) NULL,
  identification_type VARCHAR(50) NULL,
  identification_number VARCHAR(100) NULL,
  address TEXT NULL,
  emergency_contact_name VARCHAR(150) NULL,
  emergency_contact_phone VARCHAR(50) NULL,
  emergency_contact_relationship VARCHAR(50) NULL,
  blood_group VARCHAR(10) NULL,
  allergies TEXT NULL,
  medical_history TEXT NULL,
  insurance_provider VARCHAR(150) NULL,
  insurance_policy_number VARCHAR(100) NULL,
  status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  notes TEXT NULL,
  merged_into_patient_id BIGINT UNSIGNED NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_patients_org_number (organization_id, patient_number),
  KEY idx_patients_org_phone (organization_id, phone),
  KEY idx_patients_org_idnum (organization_id, identification_number),
  KEY idx_patients_name (first_name, last_name),
  KEY idx_patients_dob (date_of_birth),
  KEY idx_patients_status (status),
  CONSTRAINT fk_patients_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  CONSTRAINT fk_patients_merged_into FOREIGN KEY (merged_into_patient_id) REFERENCES patients (id) ON DELETE SET NULL,
  CONSTRAINT fk_patients_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prescribers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id INT UNSIGNED NOT NULL,
  prescriber_number VARCHAR(50) NOT NULL,
  name VARCHAR(150) NOT NULL,
  license_number VARCHAR(100) NULL,
  specialty VARCHAR(100) NULL,
  workplace VARCHAR(150) NULL,
  phone VARCHAR(50) NULL,
  email VARCHAR(100) NULL,
  address TEXT NULL,
  status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  notes TEXT NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_prescribers_org_number (organization_id, prescriber_number),
  KEY idx_prescribers_org_license (organization_id, license_number),
  KEY idx_prescribers_org_name (organization_id, name),
  KEY idx_prescribers_status (status),
  CONSTRAINT fk_prescribers_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  CONSTRAINT fk_prescribers_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prescriptions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id INT UNSIGNED NOT NULL,
  branch_id INT UNSIGNED NULL,
  prescription_number VARCHAR(50) NOT NULL,
  patient_id BIGINT UNSIGNED NOT NULL,
  prescriber_id BIGINT UNSIGNED NOT NULL,
  prescription_date DATE NOT NULL,
  expiry_date DATE NOT NULL,
  status ENUM('draft', 'pending', 'validated', 'partially_dispensed', 'fully_dispensed', 'refill_available', 'expired', 'cancelled') NOT NULL DEFAULT 'draft',
  diagnosis VARCHAR(255) NULL,
  notes TEXT NULL,
  supporting_document_url VARCHAR(255) NULL,
  validated_by INT UNSIGNED NULL,
  validated_at DATETIME NULL,
  validation_notes TEXT NULL,
  cancelled_by INT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancelled_reason TEXT NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_prescriptions_org_number (organization_id, prescription_number),
  KEY idx_prescriptions_org_patient (organization_id, patient_id),
  KEY idx_prescriptions_org_prescriber (organization_id, prescriber_id),
  KEY idx_prescriptions_branch (branch_id),
  KEY idx_prescriptions_status (status),
  KEY idx_prescriptions_dates (prescription_date, expiry_date),
  CONSTRAINT fk_prescriptions_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  CONSTRAINT fk_prescriptions_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE RESTRICT,
  CONSTRAINT fk_prescriptions_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
  CONSTRAINT fk_prescriptions_prescriber FOREIGN KEY (prescriber_id) REFERENCES prescribers (id) ON DELETE RESTRICT,
  CONSTRAINT fk_prescriptions_validated_by FOREIGN KEY (validated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_prescriptions_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_prescriptions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prescription_lines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  prescription_id BIGINT UNSIGNED NOT NULL,
  product_id INT UNSIGNED NOT NULL,
  unit_id INT UNSIGNED NULL,
  prescribed_strength VARCHAR(100) NULL,
  prescribed_dosage_form VARCHAR(100) NULL,
  prescribed_route VARCHAR(100) NULL,
  quantity_prescribed DECIMAL(12,2) NOT NULL,
  quantity_dispensed DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  quantity_remaining DECIMAL(12,2) NOT NULL,
  dosage VARCHAR(100) NOT NULL,
  frequency VARCHAR(100) NOT NULL,
  duration VARCHAR(100) NOT NULL,
  instructions TEXT NULL,
  refills_allowed INT NOT NULL DEFAULT 0,
  refills_dispensed INT NOT NULL DEFAULT 0,
  refills_remaining INT NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pl_prescription (prescription_id),
  KEY idx_pl_product (product_id),
  KEY idx_pl_unit (unit_id),
  CONSTRAINT fk_pl_prescription FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE CASCADE,
  CONSTRAINT fk_pl_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_pl_unit FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prescription_refills (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  prescription_line_id BIGINT UNSIGNED NOT NULL,
  refill_number INT NOT NULL,
  status ENUM('available', 'dispensed', 'cancelled') NOT NULL DEFAULT 'available',
  dispense_reference_id BIGINT UNSIGNED NULL,
  dispensed_at DATETIME NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_pr_line_refill_number (prescription_line_id, refill_number),
  KEY idx_pr_line (prescription_line_id),
  CONSTRAINT fk_pr_line FOREIGN KEY (prescription_line_id) REFERENCES prescription_lines (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prescription_attachments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  prescription_id BIGINT UNSIGNED NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_type VARCHAR(100) NULL,
  file_size INT NULL,
  uploaded_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pa_prescription (prescription_id),
  CONSTRAINT fk_pa_prescription FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE CASCADE,
  CONSTRAINT fk_pa_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
