-- Task 12 — Dispensing domain: dispensings, dispensing_lines, dispensing_batch_allocations.

CREATE TABLE IF NOT EXISTS dispensings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id INT UNSIGNED NOT NULL,
  branch_id INT UNSIGNED NOT NULL,
  warehouse_id INT UNSIGNED NOT NULL,
  prescription_id BIGINT UNSIGNED NOT NULL,
  patient_id BIGINT UNSIGNED NOT NULL,
  dispensing_number VARCHAR(50) NOT NULL,
  dispensing_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('draft', 'stock_allocated', 'pending_verification', 'verified', 'payment_pending', 'completed', 'rejected', 'cancelled') NOT NULL DEFAULT 'draft',
  notes TEXT NULL,
  verified_by INT UNSIGNED NULL,
  verified_at DATETIME NULL,
  verification_notes TEXT NULL,
  rejected_by INT UNSIGNED NULL,
  rejected_at DATETIME NULL,
  rejection_reason TEXT NULL,
  cancelled_by INT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancelled_reason TEXT NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_dispensings_org_number (organization_id, dispensing_number),
  KEY idx_dispensings_org_status (organization_id, status),
  KEY idx_dispensings_branch (branch_id),
  KEY idx_dispensings_warehouse (warehouse_id),
  KEY idx_dispensings_rx (prescription_id),
  KEY idx_dispensings_patient (patient_id),
  KEY idx_dispensings_date (dispensing_date),
  KEY idx_dispensings_created_by (created_by),
  CONSTRAINT fk_disp_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_disp_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_disp_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_disp_rx FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_disp_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_disp_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_disp_verifier FOREIGN KEY (verified_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_disp_rejecter FOREIGN KEY (rejected_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_disp_canceller FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dispensing_lines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  dispensing_id BIGINT UNSIGNED NOT NULL,
  prescription_line_id BIGINT UNSIGNED NOT NULL,
  product_id INT UNSIGNED NOT NULL,
  unit_id INT UNSIGNED NOT NULL,
  quantity_requested DECIMAL(14,3) NOT NULL,
  quantity_allocated DECIMAL(14,3) NOT NULL DEFAULT 0.000,
  quantity_dispensed DECIMAL(14,3) NOT NULL DEFAULT 0.000,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_dl_dispensing (dispensing_id),
  KEY idx_dl_rx_line (prescription_line_id),
  KEY idx_dl_product (product_id),
  KEY idx_dl_unit (unit_id),
  CONSTRAINT fk_dl_dispensing FOREIGN KEY (dispensing_id) REFERENCES dispensings (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_dl_rx_line FOREIGN KEY (prescription_line_id) REFERENCES prescription_lines (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_dl_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_dl_unit FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dispensing_batch_allocations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  dispensing_line_id BIGINT UNSIGNED NOT NULL,
  inventory_id INT UNSIGNED NOT NULL,
  batch_id INT UNSIGNED NOT NULL,
  storage_location_id INT UNSIGNED NOT NULL,
  unit_id INT UNSIGNED NOT NULL,
  quantity DECIMAL(14,3) NOT NULL,
  status ENUM('reserved', 'dispensed', 'released') NOT NULL DEFAULT 'reserved',
  allocated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_dba_line (dispensing_line_id),
  KEY idx_dba_inventory (inventory_id),
  KEY idx_dba_batch (batch_id),
  KEY idx_dba_location (storage_location_id),
  KEY idx_dba_status (status),
  CONSTRAINT fk_dba_line FOREIGN KEY (dispensing_line_id) REFERENCES dispensing_lines (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_dba_inventory FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_dba_batch FOREIGN KEY (batch_id) REFERENCES batches (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_dba_location FOREIGN KEY (storage_location_id) REFERENCES storage_locations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_dba_unit FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
