-- Task 15 — Stock Transfers between Branches and Warehouses.

CREATE TABLE IF NOT EXISTS stock_transfers (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id INT UNSIGNED NOT NULL,
  source_branch_id INT UNSIGNED NOT NULL,
  source_warehouse_id INT UNSIGNED NOT NULL,
  destination_branch_id INT UNSIGNED NOT NULL,
  destination_warehouse_id INT UNSIGNED NOT NULL,
  transfer_number VARCHAR(80) NOT NULL,
  status ENUM('draft', 'submitted', 'approved', 'in_transit', 'partially_received', 'completed', 'rejected', 'cancelled') NOT NULL DEFAULT 'draft',
  reason VARCHAR(255) NULL,
  notes TEXT NULL,
  requested_by INT UNSIGNED NOT NULL,
  approved_by INT UNSIGNED NULL,
  approved_at DATETIME NULL,
  rejected_by INT UNSIGNED NULL,
  rejected_at DATETIME NULL,
  rejection_reason VARCHAR(255) NULL,
  dispatched_by INT UNSIGNED NULL,
  dispatched_at DATETIME NULL,
  dispatch_notes TEXT NULL,
  received_by INT UNSIGNED NULL,
  received_at DATETIME NULL,
  receiving_notes TEXT NULL,
  cancelled_by INT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancellation_reason VARCHAR(255) NULL,
  has_discrepancy TINYINT(1) NOT NULL DEFAULT 0,
  discrepancy_resolved TINYINT(1) NOT NULL DEFAULT 0,
  discrepancy_notes TEXT NULL,
  discrepancy_resolved_by INT UNSIGNED NULL,
  discrepancy_resolved_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_stock_transfers_number (transfer_number),
  KEY idx_transfers_org_status (organization_id, status),
  KEY idx_transfers_source_wh (source_warehouse_id),
  KEY idx_transfers_dest_wh (destination_warehouse_id),
  KEY idx_transfers_requested_by (requested_by),
  CONSTRAINT fk_transfers_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_src_branch FOREIGN KEY (source_branch_id) REFERENCES branches (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_src_wh FOREIGN KEY (source_warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_dest_branch FOREIGN KEY (destination_branch_id) REFERENCES branches (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_dest_wh FOREIGN KEY (destination_warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_req_user FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_app_user FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_rej_user FOREIGN KEY (rejected_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_disp_user FOREIGN KEY (dispatched_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_recv_user FOREIGN KEY (received_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_canc_user FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfers_disc_res_user FOREIGN KEY (discrepancy_resolved_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_transfer_lines (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  transfer_id INT UNSIGNED NOT NULL,
  product_id INT UNSIGNED NOT NULL,
  unit_id INT UNSIGNED NOT NULL,
  quantity_requested DECIMAL(14,3) NOT NULL,
  quantity_approved DECIMAL(14,3) NOT NULL DEFAULT 0,
  quantity_dispatched DECIMAL(14,3) NOT NULL DEFAULT 0,
  quantity_received DECIMAL(14,3) NOT NULL DEFAULT 0,
  quantity_in_transit DECIMAL(14,3) NOT NULL DEFAULT 0,
  quantity_discrepancy DECIMAL(14,3) NOT NULL DEFAULT 0,
  discrepancy_reason VARCHAR(255) NULL,
  notes VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_transfer_lines_transfer (transfer_id),
  KEY idx_transfer_lines_product (product_id),
  CONSTRAINT fk_transfer_lines_transfer FOREIGN KEY (transfer_id) REFERENCES stock_transfers (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfer_lines_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfer_lines_unit FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_transfer_batch_allocations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  transfer_id INT UNSIGNED NOT NULL,
  transfer_line_id INT UNSIGNED NOT NULL,
  batch_id INT UNSIGNED NOT NULL,
  source_storage_location_id INT UNSIGNED NOT NULL,
  destination_storage_location_id INT UNSIGNED NULL,
  quantity_allocated DECIMAL(14,3) NOT NULL,
  quantity_dispatched DECIMAL(14,3) NOT NULL DEFAULT 0,
  quantity_received DECIMAL(14,3) NOT NULL DEFAULT 0,
  quantity_discrepancy DECIMAL(14,3) NOT NULL DEFAULT 0,
  discrepancy_reason VARCHAR(255) NULL,
  status ENUM('allocated', 'dispatched', 'received', 'discrepancy', 'cancelled') NOT NULL DEFAULT 'allocated',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_transfer_alloc_transfer (transfer_id),
  KEY idx_transfer_alloc_line (transfer_line_id),
  KEY idx_transfer_alloc_batch (batch_id),
  CONSTRAINT fk_transfer_alloc_transfer FOREIGN KEY (transfer_id) REFERENCES stock_transfers (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfer_alloc_line FOREIGN KEY (transfer_line_id) REFERENCES stock_transfer_lines (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfer_alloc_batch FOREIGN KEY (batch_id) REFERENCES batches (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfer_alloc_src_loc FOREIGN KEY (source_storage_location_id) REFERENCES storage_locations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_transfer_alloc_dest_loc FOREIGN KEY (destination_storage_location_id) REFERENCES storage_locations (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
