-- Task 16 — Stock Counting and Stock Adjustments
-- Dependency order: stock_counts -> stock_count_lines -> stock_count_line_events

CREATE TABLE IF NOT EXISTS stock_counts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  count_number VARCHAR(60) NOT NULL,
  organization_id INT UNSIGNED NOT NULL,
  branch_id INT UNSIGNED NOT NULL,
  warehouse_id INT UNSIGNED NOT NULL,
  storage_location_id INT UNSIGNED NULL,
  count_type ENUM('full', 'location', 'product') NOT NULL DEFAULT 'full',
  status ENUM(
    'draft',
    'in_progress',
    'submitted',
    'pending_approval',
    'approved',
    'completed',
    'rejected',
    'cancelled'
  ) NOT NULL DEFAULT 'draft',
  notes TEXT NULL,
  snapshot_at TIMESTAMP NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_by INT UNSIGNED NULL,
  started_at TIMESTAMP NULL,
  submitted_by INT UNSIGNED NULL,
  submitted_at TIMESTAMP NULL,
  approved_by INT UNSIGNED NULL,
  approved_at TIMESTAMP NULL,
  approval_notes TEXT NULL,
  rejection_reason TEXT NULL,
  cancellation_reason TEXT NULL,
  applied_by INT UNSIGNED NULL,
  applied_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_stock_counts_number (count_number),
  KEY idx_stock_counts_org_branch (organization_id, branch_id),
  KEY idx_stock_counts_warehouse (warehouse_id),
  KEY idx_stock_counts_status (status),
  KEY idx_stock_counts_created_at (created_at),
  CONSTRAINT fk_stock_counts_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_counts_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_counts_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_counts_location FOREIGN KEY (storage_location_id) REFERENCES storage_locations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_counts_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_counts_starter FOREIGN KEY (started_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_counts_submitter FOREIGN KEY (submitted_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_counts_approver FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_counts_applier FOREIGN KEY (applied_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_count_lines (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  stock_count_id INT UNSIGNED NOT NULL,
  storage_location_id INT UNSIGNED NOT NULL,
  product_id INT UNSIGNED NOT NULL,
  batch_id INT UNSIGNED NOT NULL,
  unit_id INT UNSIGNED NOT NULL,
  inventory_status ENUM('available', 'reserved', 'quarantined', 'damaged', 'expired', 'recalled', 'returned', 'awaiting_disposal', 'disposed') NOT NULL DEFAULT 'available',
  system_quantity DECIMAL(14,3) NOT NULL DEFAULT 0.000,
  counted_quantity DECIMAL(14,3) NULL,
  is_counted TINYINT(1) NOT NULL DEFAULT 0,
  variance_quantity DECIMAL(14,3) NULL,
  variance_reason VARCHAR(255) NULL,
  notes VARCHAR(255) NULL,
  counted_by INT UNSIGNED NULL,
  counted_at TIMESTAMP NULL,
  recount_requested TINYINT(1) NOT NULL DEFAULT 0,
  recount_notes VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_stock_count_line_pos (
    stock_count_id, storage_location_id, product_id, batch_id, unit_id, inventory_status
  ),
  KEY idx_stock_count_lines_count (stock_count_id),
  KEY idx_stock_count_lines_product (product_id),
  KEY idx_stock_count_lines_batch (batch_id),
  CONSTRAINT fk_stock_count_lines_count FOREIGN KEY (stock_count_id) REFERENCES stock_counts (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_stock_count_lines_location FOREIGN KEY (storage_location_id) REFERENCES storage_locations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_count_lines_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_count_lines_batch FOREIGN KEY (batch_id) REFERENCES batches (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_count_lines_unit FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_stock_count_lines_counter FOREIGN KEY (counted_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_count_line_events (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  stock_count_line_id INT UNSIGNED NOT NULL,
  event_type ENUM('initial_count', 'recount', 'correction', 'approved_adjustment') NOT NULL,
  previous_counted_quantity DECIMAL(14,3) NULL,
  new_counted_quantity DECIMAL(14,3) NOT NULL,
  reason VARCHAR(255) NULL,
  performed_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_count_line_events_line (stock_count_line_id),
  CONSTRAINT fk_count_line_events_line FOREIGN KEY (stock_count_line_id) REFERENCES stock_count_lines (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_count_line_events_user FOREIGN KEY (performed_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
