-- Task 17 — Quarantine Management and Product Recall Management Schema.
-- Dependency order: organizations/branches/warehouses/products/batches -> quarantine_cases, recall_cases -> recall_batches, recall_actions

CREATE TABLE IF NOT EXISTS quarantine_cases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id INT UNSIGNED NOT NULL,
  branch_id INT UNSIGNED NOT NULL,
  warehouse_id INT UNSIGNED NOT NULL,
  storage_location_id INT UNSIGNED NOT NULL,
  quarantine_number VARCHAR(50) NOT NULL,
  product_id INT UNSIGNED NOT NULL,
  batch_id INT UNSIGNED NOT NULL,
  unit_id INT UNSIGNED NOT NULL,
  quantity DECIMAL(14,3) NOT NULL,
  source_type ENUM('manual', 'inspection', 'expiry', 'recall', 'customer_complaint', 'temperature_excursion') NOT NULL DEFAULT 'manual',
  source_id BIGINT UNSIGNED NULL,
  reason VARCHAR(255) NOT NULL,
  notes TEXT NULL,
  status ENUM('quarantined', 'under_review', 'released', 'disposed', 'cancelled') NOT NULL DEFAULT 'quarantined',
  reviewed_by INT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  review_notes TEXT NULL,
  released_by INT UNSIGNED NULL,
  released_at DATETIME NULL,
  release_notes TEXT NULL,
  disposed_by INT UNSIGNED NULL,
  disposed_at DATETIME NULL,
  disposal_notes TEXT NULL,
  disposal_method VARCHAR(100) NULL,
  cancelled_by INT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancellation_reason TEXT NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_quarantine_org_number (organization_id, quarantine_number),
  KEY idx_quarantine_org_branch (organization_id, branch_id),
  KEY idx_quarantine_warehouse (warehouse_id),
  KEY idx_quarantine_product (product_id),
  KEY idx_quarantine_batch (batch_id),
  KEY idx_quarantine_status (status),
  CONSTRAINT chk_quarantine_qty_positive CHECK (quantity > 0),
  CONSTRAINT fk_quarantine_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_location FOREIGN KEY (storage_location_id) REFERENCES storage_locations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_batch FOREIGN KEY (batch_id) REFERENCES batches (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_unit FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_releaser FOREIGN KEY (released_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_disposer FOREIGN KEY (disposed_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_quarantine_canceller FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recall_cases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id INT UNSIGNED NOT NULL,
  recall_number VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  reason_category VARCHAR(100) NOT NULL,
  initiating_party VARCHAR(150) NOT NULL,
  severity ENUM('class_1', 'class_2', 'class_3') NOT NULL DEFAULT 'class_2',
  scope_level ENUM('batch', 'product') NOT NULL DEFAULT 'batch',
  product_id INT UNSIGNED NOT NULL,
  status ENUM('draft', 'under_review', 'active', 'monitoring', 'resolved', 'cancelled') NOT NULL DEFAULT 'draft',
  effective_date DATE NOT NULL,
  approved_by INT UNSIGNED NULL,
  approved_at DATETIME NULL,
  approval_notes TEXT NULL,
  activated_by INT UNSIGNED NULL,
  activated_at DATETIME NULL,
  resolved_by INT UNSIGNED NULL,
  resolved_at DATETIME NULL,
  resolution_notes TEXT NULL,
  cancelled_by INT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancellation_reason TEXT NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_recall_org_number (organization_id, recall_number),
  KEY idx_recall_org (organization_id),
  KEY idx_recall_product (product_id),
  KEY idx_recall_status (status),
  KEY idx_recall_date (effective_date),
  CONSTRAINT fk_recall_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_recall_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_recall_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_recall_approver FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_recall_activator FOREIGN KEY (activated_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_recall_resolver FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_recall_canceller FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recall_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  recall_id BIGINT UNSIGNED NOT NULL,
  batch_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_recall_batch (recall_id, batch_id),
  KEY idx_recall_batch_batch (batch_id),
  CONSTRAINT fk_recall_batch_recall FOREIGN KEY (recall_id) REFERENCES recall_cases (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_recall_batch_batch FOREIGN KEY (batch_id) REFERENCES batches (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recall_actions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  recall_id BIGINT UNSIGNED NOT NULL,
  action_type ENUM('quarantine_hold', 'supplier_return', 'disposal', 'patient_notification', 'investigation_note') NOT NULL,
  branch_id INT UNSIGNED NULL,
  warehouse_id INT UNSIGNED NULL,
  batch_id INT UNSIGNED NULL,
  quantity DECIMAL(14,3) NULL DEFAULT 0.000,
  reference_type VARCHAR(50) NULL,
  reference_id BIGINT UNSIGNED NULL,
  notes TEXT NOT NULL,
  recorded_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_recall_action_recall (recall_id),
  KEY idx_recall_action_type (action_type),
  CONSTRAINT fk_recall_action_recall FOREIGN KEY (recall_id) REFERENCES recall_cases (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_recall_action_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_recall_action_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_recall_action_batch FOREIGN KEY (batch_id) REFERENCES batches (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_recall_action_user FOREIGN KEY (recorded_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
